'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Plus, Save, ShieldCheck, Trash2, Upload } from 'lucide-react';
import Link from 'next/link';
import { collection, doc, getDoc, getDocs, setDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useApp } from '@/components/AppProvider';
import { PageShell } from '@/components/PageShell';
import { Protected } from '@/components/Protected';
import type { DramaEpisode, FilmPart, MediaItem, SubtitleTrack } from '@/lib/types';
import { uploadAdminFile } from '@/lib/storage';

type Target = { id:string; title:string; kind:'media'|'episode'|'part'; subtitles:SubtitleTrack[] };
export default function SubtitleAdmin(){
 const {user}=useApp(); const [allowed,setAllowed]=useState(false); const [targets,setTargets]=useState<Target[]>([]); const [selected,setSelected]=useState(''); const [tracks,setTracks]=useState<SubtitleTrack[]>([]); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(user)getDoc(doc(db,'admins',user.uid)).then(s=>setAllowed(s.exists()&&s.data()?.active===true))},[user]);
 useEffect(()=>{if(!allowed)return; (async()=>{const [m,e,p]=await Promise.all([getDocs(collection(db,'media')),getDocs(collection(db,'episodes')),getDocs(collection(db,'parts'))]); const all:Target[]=[...m.docs.map(d=>{const x={id:d.id,...d.data()} as MediaItem;return{id:d.id,title:x.title,kind:'media' as const,subtitles:x.subtitles||[]}}),...e.docs.map(d=>{const x={id:d.id,...d.data()} as DramaEpisode;return{id:d.id,title:`${x.title} · S${x.seasonNumber} E${x.episodeNumber}`,kind:'episode' as const,subtitles:x.subtitles||[]}}),...p.docs.map(d=>{const x={id:d.id,...d.data()} as FilmPart;return{id:d.id,title:x.title||`Part ${x.partNumber}`,kind:'part' as const,subtitles:x.subtitles||[]}})];setTargets(all);if(all[0]){setSelected(`${all[0].kind}:${all[0].id}`);setTracks(all[0].subtitles)}})()},[allowed]);
 const current=useMemo(()=>targets.find(x=>`${x.kind}:${x.id}`===selected),[targets,selected]);
 const choose=(value:string)=>{setSelected(value);const x=targets.find(t=>`${t.kind}:${t.id}`===value);setTracks(x?.subtitles||[])};
 const add=()=>setTracks(x=>[...x,{id:`sub-${Date.now()}`,src:'',label:'Badini',language:'ku',default:x.length===0}]);
 const uploadTrack=async(i:number,file?:File)=>{if(!file)return;try{const src=await uploadAdminFile(file,'subtitles');update(i,'src',src)}catch(e:any){alert(e?.message||'Subtitle upload failed.')}};
 const update=(i:number,k:keyof SubtitleTrack,v:string|boolean)=>setTracks(x=>x.map((t,n)=>n===i?{...t,[k]:v}:t));
 const remove=(i:number)=>setTracks(x=>x.filter((_,n)=>n!==i));
 const save=async()=>{if(!current)return;const clean=tracks.filter(t=>t.src.trim()&&t.label.trim()&&t.language.trim());setSaving(true);try{await setDoc(doc(db,current.kind==='media'?'media':current.kind==='episode'?'episodes':'parts',current.id),{subtitles:clean},{merge:true});setTargets(x=>x.map(t=>t===current?{...t,subtitles:clean}:t));setTracks(clean);alert('Subtitles saved.')}catch(e:any){alert(e?.message||'Save failed')}finally{setSaving(false)}};
 return <PageShell><Protected>{allowed?<div className="max-w-5xl mx-auto space-y-6"><div className="admin-hero"><div><div className="eyebrow"><ShieldCheck size={14}/> SUBTITLE STUDIO</div><h1>Subtitle Manager</h1><p>Add WebVTT subtitle tracks to films, episodes and film parts. You can upload a .vtt file or paste its public URL.</p></div><Link href="/admin" className="admin-secondary-btn"><ArrowLeft size={15}/> Admin</Link></div><div className="glass rounded-3xl p-5"><label className="block"><span className="text-xs text-slate-400 font-bold">Content</span><select className="mt-1 w-full rounded-xl px-3 py-2.5" value={selected} onChange={e=>choose(e.target.value)}>{targets.map(t=><option key={`${t.kind}:${t.id}`} value={`${t.kind}:${t.id}`}>{t.kind.toUpperCase()} — {t.title}</option>)}</select></label></div><div className="space-y-3">{tracks.map((t,i)=><div key={t.id||i} className="glass rounded-2xl p-4 grid sm:grid-cols-[1fr_1fr_1fr_auto] gap-2 items-end"><label><span className="text-xs text-slate-400">Label</span><input className="mt-1 w-full rounded-xl px-3 py-2.5" value={t.label} onChange={e=>update(i,'label',e.target.value)}/></label><label><span className="text-xs text-slate-400">Language code</span><input className="mt-1 w-full rounded-xl px-3 py-2.5" value={t.language} onChange={e=>update(i,'language',e.target.value)}/></label><label><span className="text-xs text-slate-400">.vtt URL</span><input className="mt-1 w-full rounded-xl px-3 py-2.5" value={t.src} onChange={e=>update(i,'src',e.target.value)} placeholder="https://…/subtitle.vtt"/></label><div className="flex gap-2"><label className="h-11 px-3 rounded-xl border border-white/10 grid place-items-center text-xs gap-2"><input type="checkbox" checked={!!t.default} onChange={e=>update(i,'default',e.target.checked)}/> Default</label><label className="h-11 px-3 rounded-xl border border-white/10 grid place-items-center text-xs gap-2 cursor-pointer"><Upload size={14}/><span>Upload VTT</span><input type="file" accept=".vtt,text/vtt" className="hidden" onChange={e=>uploadTrack(i,e.target.files?.[0])}/></label><button type="button" onClick={()=>remove(i)} className="mini-btn"><Trash2 size={15}/></button></div></div>)}{!tracks.length&&<div className="glass rounded-2xl p-10 text-center text-slate-500">No subtitle tracks yet.</div>}</div><div className="flex gap-2"><button type="button" onClick={add} className="admin-secondary-btn"><Plus size={16}/> Add track</button><button type="button" onClick={save} disabled={!current||saving} className="admin-primary-btn"><Save size={16}/>{saving?'Saving…':'Save subtitles'}</button></div></div>:<div className="min-h-[50vh] grid place-items-center text-slate-500">Admin access required.</div>}</Protected></PageShell>
}
