'use client';
import { useEffect, useMemo, useState } from 'react';
import { collection, deleteDoc, doc, getDoc, getDocs, orderBy, query, serverTimestamp, updateDoc, setDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { PageShell } from '@/components/PageShell';
import { Protected } from '@/components/Protected';
import type { Channel, MediaItem, UserProfile, Category, PlayerType } from '@/lib/types';
import { Edit3, Film, Loader2, Plus, Radio, Save, ShieldCheck, Trash2, UserCheck, UserX, X } from 'lucide-react';
import { useApp } from '@/components/AppProvider';

const categories: Category[] = ['NEWS','SPORTS','BEIN','MOVIES','KIDS','KURDISH','ENTERTAINMENT'];
const emptyChannel: Channel = { id:'', name:'', category:'NEWS', description:'', logo:'', streamUrl:'', playerType:'video', enabled:false };
const emptyMedia: MediaItem = { id:'', title:'', type:'film', year:new Date().getFullYear(), genre:'', description:'', poster:'', streamUrl:'', playerType:'video', enabled:false };

export default function Admin(){
 const {user,t}=useApp(); const [allowed,setAllowed]=useState(false); const [users,setUsers]=useState<UserProfile[]>([]); const [channels,setChannels]=useState<Channel[]>([]); const [media,setMedia]=useState<MediaItem[]>([]); const [tab,setTab]=useState<'users'|'channels'|'media'>('users'); const [channelForm,setChannelForm]=useState<Channel>(emptyChannel); const [mediaForm,setMediaForm]=useState<MediaItem>(emptyMedia); const [editingChannel,setEditingChannel]=useState<string|null>(null); const [editingMedia,setEditingMedia]=useState<string|null>(null); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
 const load=async()=>{if(!user)return;setBusy('load');try{const [us,cs,ms]=await Promise.all([getDocs(query(collection(db,'users'),orderBy('createdAt','desc'))).catch(()=>getDocs(collection(db,'users'))),getDocs(collection(db,'channels')),getDocs(collection(db,'media'))]);setUsers(us.docs.map(d=>d.data() as UserProfile));setChannels(cs.docs.map(d=>({id:d.id,...d.data()} as Channel)));setMedia(ms.docs.map(d=>({id:d.id,...d.data()} as MediaItem)));}finally{setBusy('');}};
 useEffect(()=>{if(!user)return;getDoc(doc(db,'admins',user.uid)).then(s=>setAllowed(s.exists()&&s.data()?.active===true));},[user]);
 useEffect(()=>{if(allowed)load();},[allowed]);
 const saveChannel=async()=>{if(!channelForm.name.trim())return setMessage('Channel name is required.');const id=channelForm.id.trim()||channelForm.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`channel-${Date.now().toString(36)}`;setBusy('channel');try{await setDoc(doc(db,'channels',id),{...channelForm,id,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true});setMessage('Channel saved.');setEditingChannel(null);setChannelForm(emptyChannel);await load();}catch(e:any){setMessage(e?.message||'Could not save channel.');}finally{setBusy('');}};
 const saveMedia=async()=>{if(!mediaForm.title.trim())return setMessage('Title is required.');const id=mediaForm.id.trim()||mediaForm.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`media-${Date.now().toString(36)}`;setBusy('media');try{await setDoc(doc(db,'media',id),{...mediaForm,id,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true});setMessage('Film/Drama saved.');setEditingMedia(null);setMediaForm(emptyMedia);await load();}catch(e:any){setMessage(e?.message||'Could not save media.');}finally{setBusy('');}};
 const remove=async(type:'channels'|'media',id:string)=>{if(!confirm('Delete this item?'))return;setBusy(id);try{await deleteDoc(doc(db,type,id));await load();setMessage('Deleted.');}finally{setBusy('');}};
 const change=async(u:UserProfile,status:'active'|'disabled')=>{setBusy(u.uid);try{await updateDoc(doc(db,'users',u.uid),{status});setUsers(x=>x.map(a=>a.uid===u.uid?{...a,status}:a));}finally{setBusy('');}};
 const activeChannels=useMemo(()=>channels.filter(x=>x.enabled).length,[channels]); const activeMedia=useMemo(()=>media.filter(x=>x.enabled).length,[media]);
 if(!user) return <PageShell><div className="min-h-[50vh] grid place-items-center text-slate-400">Loading…</div></PageShell>;
 return <PageShell><Protected>{allowed?<div className="space-y-7">
   <div className="flex flex-col lg:flex-row lg:items-center gap-4 justify-between"><div className="flex items-center gap-3"><div className="h-12 w-12 rounded-2xl bg-violet-500/10 text-violet-300 grid place-items-center"><ShieldCheck/></div><div><h1 className="text-3xl font-black">Admin Console</h1><p className="text-slate-400">Users, channels, films and drama</p></div></div><div className="text-xs text-slate-500">Firestore is the live content source</div></div>
   {message&&<div className="glass rounded-xl p-3 text-sm text-violet-200 flex items-center justify-between"><span>{message}</span><button onClick={()=>setMessage('')}><X size={16}/></button></div>}
   <div className="grid grid-cols-3 gap-3"><Stat label="Users" value={users.length}/><Stat label="Channels" value={`${activeChannels}/${channels.length}`}/><Stat label="Media" value={`${activeMedia}/${media.length}`}/></div>
   <div className="flex gap-2 overflow-x-auto pb-1"><Tab active={tab==='users'} onClick={()=>setTab('users')} icon={<ShieldCheck size={16}/>} label="Users"/><Tab active={tab==='channels'} onClick={()=>setTab('channels')} icon={<Radio size={16}/>} label="Channels"/><Tab active={tab==='media'} onClick={()=>setTab('media')} icon={<Film size={16}/>} label="Films & Drama"/></div>
   {tab==='users'&&<div className="glass rounded-2xl overflow-hidden"><div className="p-4 border-b border-white/10 text-sm font-bold">Registered users · {users.length}</div><div className="divide-y divide-white/5">{users.map(u=><div key={u.uid} className="p-4 flex flex-col sm:flex-row gap-4 sm:items-center"><div className="flex-1"><div className="font-bold">{u.name}</div><div className="text-xs text-slate-500 mt-1">{u.email}</div></div><div className="text-xs px-2.5 py-1 rounded-full bg-white/5 capitalize">{u.status}</div><div className="flex gap-2"><button disabled={busy===u.uid} onClick={()=>change(u,'active')} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-emerald-500/10 text-emerald-200 text-xs"><UserCheck size={14}/>{t('activate')}</button><button disabled={busy===u.uid} onClick={()=>change(u,'disabled')} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-red-500/10 text-red-200 text-xs"><UserX size={14}/>{t('disable')}</button></div></div>)}</div></div>}
   {tab==='channels'&&<ContentManager type="channel" items={channels} form={channelForm} setForm={setChannelForm} editing={editingChannel} setEditing={setEditingChannel} save={saveChannel} remove={remove} busy={busy} />}
   {tab==='media'&&<ContentManager type="media" items={media} form={mediaForm} setForm={setMediaForm} editing={editingMedia} setEditing={setEditingMedia} save={saveMedia} remove={remove} busy={busy} />}
 </div>:<div className="min-h-[50vh] grid place-items-center text-center"><div><ShieldCheck className="mx-auto text-red-300" size={38}/><h1 className="text-2xl font-bold mt-4">Access denied</h1><p className="text-slate-500 mt-2">This account is not an administrator.</p></div></div>}</Protected></PageShell>
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="glass rounded-2xl p-4"><div className="text-xs text-slate-500">{label}</div><div className="text-2xl font-black mt-1">{value}</div></div>}
function Tab({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string}){return <button onClick={onClick} className={`inline-flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold whitespace-nowrap ${active?'bg-white text-slate-950':'glass text-slate-300'}`}>{icon}{label}</button>}
function ContentManager({type,items,form,setForm,editing,setEditing,save,remove,busy}:{type:'channel'|'media';items:any[];form:any;setForm:(x:any)=>void;editing:string|null;setEditing:(x:string|null)=>void;save:()=>void;remove:(type:'channels'|'media',id:string)=>void;busy:string}){
 const isChannel=type==='channel'; const list=items as (Channel|MediaItem)[];
 const edit=(item:any)=>{setForm({...item});setEditing(item.id)};
 return <div className="grid xl:grid-cols-[390px_1fr] gap-5">
  <div className="glass rounded-2xl p-5 h-fit space-y-4"><div className="flex items-center justify-between"><h2 className="font-black">{editing?'Edit':'Add'} {isChannel?'Channel':form.type==='drama'?'Drama':'Film'}</h2>{editing&&<button onClick={()=>{setEditing(null);setForm(isChannel?emptyChannel:emptyMedia)}}><X size={17}/></button>}</div>
   {isChannel?<><Field label="ID"><input value={form.id} disabled={!!editing} onChange={e=>setForm({...form,id:e.target.value})} placeholder="channel-id"/></Field><Field label="Name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Channel name"/></Field><Field label="Category"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Logo URL"><input value={form.logo||''} onChange={e=>setForm({...form,logo:e.target.value})} placeholder="https://..."/></Field><Field label="Stream URL"><input value={form.streamUrl||''} onChange={e=>setForm({...form,streamUrl:e.target.value})} placeholder="Authorized stream URL"/></Field><Field label="Player"><select value={form.playerType||'video'} onChange={e=>setForm({...form,playerType:e.target.value as PlayerType})}><option value="video">Video / HLS</option><option value="iframe">Iframe</option></select></Field><Field label="Description"><textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></Field></>:<><Field label="ID"><input value={form.id} disabled={!!editing} onChange={e=>setForm({...form,id:e.target.value})} placeholder="movie-id"/></Field><Field label="Title"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Title"/></Field><Field label="Type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="film">Film</option><option value="drama">Drama</option></select></Field><Field label="Year"><input type="number" value={form.year} onChange={e=>setForm({...form,year:Number(e.target.value)})}/></Field><Field label="Genre"><input value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})} placeholder="Action, Drama..."/></Field><Field label="Poster URL"><input value={form.poster} onChange={e=>setForm({...form,poster:e.target.value})} placeholder="https://..."/></Field><Field label="Video URL"><input value={form.streamUrl||''} onChange={e=>setForm({...form,streamUrl:e.target.value})} placeholder="Authorized video/HLS URL"/></Field><Field label="Player"><select value={form.playerType||'video'} onChange={e=>setForm({...form,playerType:e.target.value as PlayerType})}><option value="video">Video / HLS</option><option value="iframe">Iframe</option></select></Field><Field label="Description"><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></>}
   <label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={!!form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><span>Active / visible to users</span></label>
   <button onClick={save} disabled={busy===type} className="w-full inline-flex items-center justify-center gap-2 py-3 rounded-xl bg-white text-slate-950 font-black">{busy===type?<Loader2 className="animate-spin" size={17}/>:editing?<Save size={17}/>:<Plus size={17}/>} {editing?'Save changes':'Add'}</button>
  </div>
  <div className="glass rounded-2xl overflow-hidden"><div className="p-4 border-b border-white/10 font-bold">{isChannel?'Channels':'Films & Drama'} · {list.length}</div><div className="divide-y divide-white/5">{list.map((item:any)=><div key={item.id} className="p-4 flex gap-3 items-center"><div className="h-12 w-12 rounded-xl overflow-hidden bg-white/5 shrink-0 grid place-items-center">{isChannel&&item.logo?<img src={item.logo} className="w-full h-full object-cover" alt=""/>:isChannel?<Radio size={18} className="text-violet-300"/>:item.poster?<img src={item.poster} className="w-full h-full object-cover" alt=""/>:<Film size={18} className="text-violet-300"/>}</div><div className="flex-1 min-w-0"><div className="font-bold truncate">{isChannel?item.name:item.title}</div><div className="text-xs text-slate-500 mt-1">{isChannel?item.category:`${item.type} · ${item.year}`} · {item.enabled?'Active':'Disabled'}</div></div><button onClick={()=>edit(item)} className="p-2 rounded-lg hover:bg-white/5" title="Edit"><Edit3 size={16}/></button><button onClick={()=>remove(isChannel?'channels':'media',item.id)} disabled={busy===item.id} className="p-2 rounded-lg hover:bg-red-500/10 text-red-300" title="Delete"><Trash2 size={16}/></button></div>)}</div>{!list.length&&<div className="p-10 text-center text-slate-500">No items yet. Add a channel, film or drama from the form.</div>}</div>
 </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="text-xs text-slate-400 font-bold">{label}</span><div className="mt-1 [&_input]:w-full [&_input]:glass [&_input]:rounded-xl [&_input]:px-3 [&_input]:py-2.5 [&_input]:outline-none [&_select]:w-full [&_select]:glass [&_select]:rounded-xl [&_select]:px-3 [&_select]:py-2.5 [&_select]:outline-none [&_textarea]:w-full [&_textarea]:glass [&_textarea]:rounded-xl [&_textarea]:px-3 [&_textarea]:py-2.5 [&_textarea]:outline-none [&_textarea]:min-h-20">{children}</div></label>}
