'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Clock3, LockKeyhole, Play, PlayCircle, Star } from 'lucide-react';
import { useParams } from 'next/navigation';
import { PageShell } from '@/components/PageShell';
import { Protected } from '@/components/Protected';
import { getEpisodes, getMedia, getMediaById } from '@/lib/content';
import { useApp } from '@/components/AppProvider';
import { MovieMeta } from '@/components/MovieMeta';
import { getBackdrop, getLogo } from '@/lib/media-meta';
import type { DramaEpisode, MediaItem } from '@/lib/types';

export default function DramaDetails(){
 const {isVip}=useApp(); const params=useParams<{id:string}>(); const id=decodeURIComponent(params.id); const [drama,setDrama]=useState<MediaItem|null>(null); const [episodes,setEpisodes]=useState<DramaEpisode[]>([]); const [related,setRelated]=useState<MediaItem[]>([]);
 useEffect(()=>{getMediaById(id).then(setDrama).catch(()=>setDrama(null));},[id]);
 useEffect(()=>{getEpisodes(id,isVip).then(setEpisodes).catch(()=>setEpisodes([]));},[id,isVip]);
 useEffect(()=>{getMedia(true,isVip).then(all=>setRelated(all.filter(x=>x.type==='drama'&&x.id!==id&&x.enabled!==false).slice(0,6))).catch(()=>{});},[id,isVip]);
 const seasons=useMemo(()=>Array.from(new Set(episodes.map(e=>e.seasonNumber))).sort((a,b)=>a-b),[episodes]); const logo=drama?getLogo(drama):undefined; const backdrop=drama?getBackdrop(drama):'';
 return <PageShell><Protected>{drama?.type==='drama'?<div className="max-w-6xl mx-auto space-y-8">
 <Link href="/drama" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16}/> Drama</Link>
 <section className="relative overflow-hidden rounded-[2rem] glass min-h-[500px]"><img src={backdrop} alt="" className="absolute inset-0 w-full h-full object-cover opacity-25" loading="eager"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/35"/><div className="relative grid lg:grid-cols-[250px_1fr] gap-7 p-5 sm:p-9 items-end min-h-[500px]"><div className="aspect-[2/3] rounded-2xl overflow-hidden bg-slate-900 shadow-2xl"><img src={drama.poster} alt={drama.title} className="w-full h-full object-cover"/></div><div className="pb-1 max-w-3xl">{logo?<img src={logo} alt={drama.title} className="max-h-20 max-w-[280px] object-contain object-left mb-4"/>:<h1 className="text-4xl sm:text-6xl font-black">{drama.title}</h1>}<MovieMeta item={drama}/><p className="text-slate-300 leading-7 mt-5">{drama.description}</p><div className="mt-6 flex flex-wrap gap-3">{episodes[0]&&<Link href={`/watch?episode=${encodeURIComponent(episodes[0].id)}`} className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-white text-slate-950 font-black"><Play size={17} fill="currentColor"/> Start watching</Link>}{drama.accessLevel==='vip'&&<span className="inline-flex items-center gap-2 px-4 py-3 rounded-xl bg-violet-500/15 text-violet-200 font-black"><LockKeyhole size={16}/> VIP</span>}</div></div></div></section>
 {drama.status&&<div className="text-xs text-slate-500">Status: <span className="text-slate-300 font-bold">{drama.status}</span></div>}
 {seasons.map(season=>{const list=episodes.filter(e=>e.seasonNumber===season);return <section key={season} className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Season {season}</h2><span className="text-xs text-slate-500">{list.length} episodes</span></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{list.map(ep=><Link key={ep.id} href={`/watch?episode=${encodeURIComponent(ep.id)}`} className="glass rounded-2xl p-3 flex items-center gap-3 hover:bg-white/[.07] transition"><span className="h-16 w-24 rounded-xl bg-slate-900 overflow-hidden shrink-0 grid place-items-center">{ep.thumbnail?<img src={ep.thumbnail} alt="" loading="lazy" className="w-full h-full object-cover"/>:<span className="text-violet-300 font-black">{String(ep.episodeNumber).padStart(2,'0')}</span>}</span><div className="min-w-0 flex-1"><div className="font-bold truncate">E{ep.episodeNumber} · {ep.title}</div><div className="text-xs text-slate-500 mt-1 flex items-center gap-2"><Clock3 size={12}/>{ep.durationMinutes?`${ep.durationMinutes} min`:'Episode'}{ep.quality?.length&&<><span>•</span><span>{ep.quality.join(' / ')}</span></>}{ep.accessLevel==='vip'&&<><span>•</span><span className="text-violet-300">VIP</span></>}</div>{ep.subtitles?.length&&<div className="text-[11px] text-emerald-300 mt-1">{ep.subtitles.length} subtitle track{ep.subtitles.length>1?'s':''}</div>}</div><PlayCircle size={20} className="text-slate-400"/></Link>)}</div></section>})}
 {!episodes.length&&<div className="glass rounded-2xl p-10 text-center text-slate-500">No episodes are available for this access level yet.</div>}
 {related.length>0&&<section><h2 className="text-xl font-black mb-3">More drama</h2><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">{related.map(x=><Link key={x.id} href={`/drama/${encodeURIComponent(x.id)}`} className="glass rounded-xl overflow-hidden"><img src={x.poster} alt={x.title} loading="lazy" className="aspect-[2/3] w-full object-cover"/><div className="p-2"><div className="text-sm font-bold truncate">{x.title}</div>{x.rating!=null&&<div className="text-xs text-slate-500 flex items-center gap-1"><Star size={11} fill="currentColor"/> {x.rating.toFixed(1)}</div>}</div></Link>)}</div></section>}
 </div>:<div className="min-h-[60vh] grid place-items-center text-slate-500">Drama not found.</div>}</Protected></PageShell>;
}
